name: ci

on:
  pull_request:
    branches: [main]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Run go tests
        run: go test ./... -cover
  style:
    name: Style
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      
      - name: Install staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@latest
     
      - name: Test go formatting
        run: test -z $(go fmt ./...)

      -name: Run staticcheck
        run: staticcheck ./...